# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'test_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12test_service.proto\x12\x0btestservice\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\".\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"3\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x0c\x45\x63hoResponse\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"$\n\x13SetStringParRequest\x12\r\n\x05value\x18\x01 \x01(\t\"8\n\x14SetStringParResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xa4\x01\n\x11\x43\x61lculatorRequest\x12;\n\toperation\x18\x01 \x01(\x0e\x32(.testservice.CalculatorRequest.Operation\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\"<\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\"F\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xfb\x02\n\x11\x43\x61lculatorService\x12\x38\n\x03\x41\x64\x64\x12\x17.testservice.AddRequest\x1a\x18.testservice.AddResponse\x12G\n\x08Multiply\x12\x1c.testservice.MultiplyRequest\x1a\x1d.testservice.MultiplyResponse\x12;\n\x04\x45\x63ho\x12\x18.testservice.EchoRequest\x1a\x19.testservice.EchoResponse\x12S\n\x0cSetStringPar\x12 .testservice.SetStringParRequest\x1a!.testservice.SetStringParResponse\x12Q\n\nCalculator\x12\x1e.testservice.CalculatorRequest\x1a\x1f.testservice.CalculatorResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=35
  _globals['_ADDREQUEST']._serialized_end=69
  _globals['_ADDRESPONSE']._serialized_start=71
  _globals['_ADDRESPONSE']._serialized_end=117
  _globals['_MULTIPLYREQUEST']._serialized_start=119
  _globals['_MULTIPLYREQUEST']._serialized_end=158
  _globals['_MULTIPLYRESPONSE']._serialized_start=160
  _globals['_MULTIPLYRESPONSE']._serialized_end=211
  _globals['_ECHOREQUEST']._serialized_start=213
  _globals['_ECHOREQUEST']._serialized_end=240
  _globals['_ECHORESPONSE']._serialized_start=242
  _globals['_ECHORESPONSE']._serialized_end=289
  _globals['_SETSTRINGPARREQUEST']._serialized_start=291
  _globals['_SETSTRINGPARREQUEST']._serialized_end=327
  _globals['_SETSTRINGPARRESPONSE']._serialized_start=329
  _globals['_SETSTRINGPARRESPONSE']._serialized_end=385
  _globals['_CALCULATORREQUEST']._serialized_start=388
  _globals['_CALCULATORREQUEST']._serialized_end=552
  _globals['_CALCULATORREQUEST_OPERATION']._serialized_start=492
  _globals['_CALCULATORREQUEST_OPERATION']._serialized_end=552
  _globals['_CALCULATORRESPONSE']._serialized_start=554
  _globals['_CALCULATORRESPONSE']._serialized_end=624
  _globals['_CALCULATORSERVICE']._serialized_start=627
  _globals['_CALCULATORSERVICE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
