# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_service_pb2 as test__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculatorServiceStub(object):
    """Calculator service for testing AsyncioDAT gRPC integration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/testservice.CalculatorService/Add',
                request_serializer=test__service__pb2.AddRequest.SerializeToString,
                response_deserializer=test__service__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/testservice.CalculatorService/Multiply',
                request_serializer=test__service__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=test__service__pb2.MultiplyResponse.FromString,
                _registered_method=True)
        self.Echo = channel.unary_unary(
                '/testservice.CalculatorService/Echo',
                request_serializer=test__service__pb2.EchoRequest.SerializeToString,
                response_deserializer=test__service__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.SetStringPar = channel.unary_unary(
                '/testservice.CalculatorService/SetStringPar',
                request_serializer=test__service__pb2.SetStringParRequest.SerializeToString,
                response_deserializer=test__service__pb2.SetStringParResponse.FromString,
                _registered_method=True)
        self.Calculator = channel.stream_stream(
                '/testservice.CalculatorService/Calculator',
                request_serializer=test__service__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=test__service__pb2.CalculatorResponse.FromString,
                _registered_method=True)


class CalculatorServiceServicer(object):
    """Calculator service for testing AsyncioDAT gRPC integration
    """

    def Add(self, request, context):
        """Simple unary operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStringPar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Calculator(self, request_iterator, context):
        """Bidirectional streaming calculator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=test__service__pb2.AddRequest.FromString,
                    response_serializer=test__service__pb2.AddResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=test__service__pb2.MultiplyRequest.FromString,
                    response_serializer=test__service__pb2.MultiplyResponse.SerializeToString,
            ),
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=test__service__pb2.EchoRequest.FromString,
                    response_serializer=test__service__pb2.EchoResponse.SerializeToString,
            ),
            'SetStringPar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStringPar,
                    request_deserializer=test__service__pb2.SetStringParRequest.FromString,
                    response_serializer=test__service__pb2.SetStringParResponse.SerializeToString,
            ),
            'Calculator': grpc.stream_stream_rpc_method_handler(
                    servicer.Calculator,
                    request_deserializer=test__service__pb2.CalculatorRequest.FromString,
                    response_serializer=test__service__pb2.CalculatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testservice.CalculatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('testservice.CalculatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculatorService(object):
    """Calculator service for testing AsyncioDAT gRPC integration
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testservice.CalculatorService/Add',
            test__service__pb2.AddRequest.SerializeToString,
            test__service__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testservice.CalculatorService/Multiply',
            test__service__pb2.MultiplyRequest.SerializeToString,
            test__service__pb2.MultiplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testservice.CalculatorService/Echo',
            test__service__pb2.EchoRequest.SerializeToString,
            test__service__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStringPar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/testservice.CalculatorService/SetStringPar',
            test__service__pb2.SetStringParRequest.SerializeToString,
            test__service__pb2.SetStringParResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Calculator(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/testservice.CalculatorService/Calculator',
            test__service__pb2.CalculatorRequest.SerializeToString,
            test__service__pb2.CalculatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
